### ISSUE TITLE
YACC Plugin - Require Valid JIRA Issue

### ISSUE THREAD

**Issue by soodsaks** [sford/yet-another-commit-checker#101]
We have detected a possible issue with the YACC plugin in that it only appears to work with the primary connected JIRA instance (genjira) and not the other connected JIRA instances.
Require valid jira issue key is already checked under YACC.
Application links are configured properly for both Stash and JIra.

**Comment by drcollatz** [comment]
Exact the same behaviour here. On primary instance everything works fine but not on the other ones...

**Comment by sford** [comment]
Hi @soodsaks  and @drcollatz,

Only the primary JIRA instance is currently checked. It has been recently a widely requested feature to check all instances :-) As @drcollatz  notes, there has been some progress made on this. When I have some time, I will see what needs to be done to get that merge. My guess is that should be the next big YACC feature considering how often people are asking for it :-)

**Comment by marlang** [comment]
Hi.  I consider this a bug because my customers need this to work but i can't make their instance the primary one.  I asked a question here - https://answers.atlassian.com/questions/35758520/yacc-is-not-working-between-jira-and-bitbucket-server.  I'm also stuck at version 1.6 because we haven't been able to upgrade to 4.x yet and ran into the global configuration bug.  What versions will this be fixed on?

**Comment by sford** [comment]
HI @marlang , it will probably only be fixed in the latest version of YACC. At least, there are significant API changes between Stash 3.x and 4.x which could make backporting a bit more work than just cherry picking a commit. It will be more clear when #101 is fixed (on the TODO list)

**Comment by marlang** [comment]
Are there any updates to this one?  We are now upgraded to 4.3.2 and still experiencing issues.  I see that the bug is still open and our customer is asking again when to expect this to be fixed.  Thanks.

**Comment by sford** [comment]
Closing as duplicate, see #94
