### ISSUE TITLE
Branch Name Regex

### ISSUE THREAD

**Issue by KevinSheedy** [sford/yet-another-commit-checker#102]
Getting the following error trying to push a feature branch:

    Invalid branch name. 'feature/commit-checker' does not match regex 'feature*|bugfix*'

However, testing the regex on [regexpal](http://www.regexpal.com/) it does match.

I also tried the example regex and got this error:

     Invalid branch name. 'feature/commit-checker' does not match regex 'master|(?:(?:bugfix|hotfix|feature)/[A-Z]+-\d+-.+)'

**Comment by sford** [comment]
Hi @KevinSheedy ,

That regex is actually inaccurate to match that branch. The `e*` portion is matching 0 or more e's, so the valid branches will be `featur`, `feature`, or `featureeeee`. 

When testing using regexpal, you will see that it is only matching the branch partially (the part that it highlights).

If you want to match `/` and everything after it in the branch name, you will need to do something like `.*`, as in `feature.*`.

**Comment by KevinSheedy** [comment]
Thanks @sford.
Could I suggest adding a simpler regex example to the Branch Name Regex section of the README.md, something like:

    feature/.*|bugfix/.*

**Comment by sford** [comment]
:+1:
