### ISSUE TITLE
Missing something obvious with Exclude by Regex option

### ISSUE THREAD

**Issue by avggeek** [sford/yet-another-commit-checker#107]
Hi,
I use etckeeper to manage server configurations, which generates automatic commits whenever I update packages using a package manager. These automatic commits generally use the commit message `"committing changes in /etc after apt run"`.

I'm trying to skip the commit checks by using the Exclude by Regex option. However, I can't seem to get this to work using the regex `(.*)apt\srun(.*)` or `apt\srun` or even just `apt run`. 

I'm running version 1.8 of the plugin on Stash version 3.11.1. Could you please help me figure out what I am doing wrong?

**Comment by sford** [comment]
In that example, `apt run` should have worked. Can you include the commit that is experiencing the problem (from `git log`) and the YACC output when it is pushed?

**Comment by avggeek** [comment]
Hi Sean,

I checked again using the regex `apt run` and was able to push a commit to the repository even with YACC enabled. My apologies - I guess I did not actually test that regex after setting it up.

**Comment by sford** [comment]
Glad it is working!
