### ISSUE TITLE
YACC plugin - Valid jira issue key checks fails for multiple jira instances

### ISSUE THREAD

**Issue by aswinnair123** [sford/yet-another-commit-checker#112]
Our BBS is integrated to multiple Jira instance through application links, ( jira_applink screen is attached ).
We use YACC plugin (yacc plugin confn is attached as image) to check valid jira key from the commit message, this plugin is doing this check only to one jira instance (ficc jira instance) which is the one configured as primary.
Valid jira issue key checks is failing for other jira instances. Could you please help on this to fix ? Please let me know if you need further information.
Regards
Aswin

**Comment by sford** [comment]
Hi @aswinnair123 , 

The currently released version of YACC does not support multiple JIRA instances. 

However, can you please check out #94, specifically [this comment](https://github.com/sford/yet-another-commit-checker/issues/94#issuecomment-220847979)? Basically, I have a development YACC build that _does_ support multiple JIRA instances. I have tested it locally, but I don't have a production environment that uses multiple JIRA instances. So, I need help from someone to verify that everything looks good before releasing it. I don't want to push it live right this second until I get some feedback.

Thanks!

Going to close this as duplicate... see #94.

**Comment by aswinnair123** [comment]
Hi We have done a basic testing on our Dev instance, it is working fine. We leave this out for developers to test and awaiting for the feedback. We will get back to you.
Regards
Aswin
