### ISSUE TITLE
YACC plugin for multiple jira instances

### ISSUE THREAD

**Issue by aswinnair123** [sford/yet-another-commit-checker#113]
Hi

I am not able to make any comment on the earlier ticket raised below.  We are done our testing on DEV instance and the beta version that you provided is working fine with multiple jira instances. We would try this to implement in UAT and then to PROD instances.

should we try the same jar to UAT and PROD, or do you have any newer version of YACC plugin ? Please suggest

https://github.com/sford/yet-another-commit-checker/issues/112

**Comment by sford** [comment]
I would use the same jar... I am out of the country and not able to put a release together right at this time. Thanks for the help testing!

**Comment by aswinnair123** [comment]
Hi, Please let us know when can i expect the RELEASE version of this jar, so i can implement this in UAT and then in PROD ?

**Comment by aswinnair123** [comment]
Hi, Please let us know when can i expect the RELEASE version of this jar, so i can implement this in UAT and then in PROD ?

**Comment by aswinnair123** [comment]
Hi, Please let us know when can i expect the RELEASE version of this jar, so i can implement this in UAT and then in PROD ?

**Comment by aswinnair123** [comment]
Hi, Could you please provide a release version the jar ?

**Comment by aswinnair123** [comment]
Hi, Could you please provide a release version the jar ?

**Comment by sford** [comment]
Closing as fixed.
