### ISSUE TITLE
YACC Not Working with Tortoise

### ISSUE THREAD

**Issue by timrazik** [sford/yet-another-commit-checker#118]
I'm hoping someone can help me.  Maybe this is user error so I thought I would reach out to the experts.

We have a complex regex to validate the commit message.  The message must be a comma delimited list of issues followed by a : and a comment.   When using TortoiseGit to push a commit it fails.

Example messages
UST-1 : Testing Yacc commit
UST-1,  TR12345 : Sample of two issues listed together

This is the regex we use:
(?s)^((([A-Z]{2}[0-9]{4,}(\\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*))((\\s)*,(\\s)*((([A-Z]{2}[0-9]{4,}(\\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*)))*(\\:)(\\s*)\\w{1,}.*

It returns an error saying the commit message does not match the regular expression.  I took the java code for Yacc and tested my strings using a simple java main app and the strings pass.

I'm guessing that there is something extra in the string passed by tortoise but I don't see anything in the logs and the tortoise log the message looks fine.

I also try it over a command line and have the same issue.

> C:\dev\upoint_poc\githooktest>git add timtest/test.txt
> 
> C:\dev\upoint_poc\githooktest>git commit -m"UST-1 : this should work"
> ------------- PRE COMMIT
> 
> ------------------
> /mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/h/bin:/cmd:/c/oraclexe/app/oracle/product/11.2.0/se
> rver/bin:/c/dev/Gradle/gradle-2.9/bin:/c/Oracle/product/11.2.0/bin:/c/WINDOWS/system32:/c/WINDOWS:/c
> /WINDOWS/System32/Wbem:/c/WINDOWS/system32/nls:/c/WINDOWS/system32/nls/ENGLISH:/c/Program Files (x86
> )/UltraEdit:/c/Program Files (x86)/RSA SecurID Token Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOW
> S/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Java/jre7/bin:/c/P
> rogram Files/Lenovo/Fingerprint Manager Pro:/c/Program Files/SSH/Clients:/c/Program Files/SourceGear
> /Common/DiffMerge:/c/Program Files/TortoiseSVN/bin:/c/Program Files (x86)/IBM/SQLLIB_01/BIN:/c/Progr
> am Files (x86)/IBM/SQLLIB_01/FUNCTION:/c/Program Files (x86)/IBM/SQLLIB_01/BIN:/c/Program Files (x86
> )/IBM/SQLLIB_01/FUNCTION:/c/Program Files/TortoiseGit/bin
> --------------------
> 
> -----------------
> 
> .git/COMMIT_EDITMSG message
> UST-1 : this should work
> ankita.docx timtest
> [razik 7d00a50] UST-1 : this should work
>  1 file changed, 1 insertion(+), 1 deletion(-)
> 
> C:\dev\upoint_poc\githooktest>git push -u origin razik:master
> Counting objects: 8, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (4/4), done.
> Writing objects: 100% (8/8), 681 bytes | 0 bytes/s, done.
> Total 8 (delta 0), reused 0 (delta 0)
> remote: Your comment is not bob!
> remote:
> remote: refs/heads/master: 65b7c3e3bdce115dfad8048c9856867c4a21cc0f: commit message doesn't match re
> gex: (?s)((([A-Z]{2}[0-9]{4,}(\\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*))((\\s)*,(\\s)*((([A-Z]{2}[0-9]{4,}(
> \\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*)))*(\\:)(\\s*)\\w{1,}.*
> remote:
> remote: refs/heads/master: 7d00a508c9ada46e42b60dc6a7d2d8c3f58cc65b: commit message doesn't match re
> gex: (?s)((([A-Z]{2}[0-9]{4,}(\\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*))((\\s)*,(\\s)*((([A-Z]{2}[0-9]{4,}(
> \\s)*)|[A-Za-z_0-9]+-[0-9]+(\\s)*)))*(\\:)(\\s*)\\w{1,}.*
> remote:
> To http://10.80.31.216:9382/scm/upt/githooktest.git
>  ! [remote rejected] razik -> master (pre-receive hook declined)
> error: failed to push some refs to 'http://10.80.31.216:9382/scm/upt/githooktest.git'
> 
>

**Comment by timrazik** [comment]
I have an update.  As soon as I clicked save here I realized that we used the java notaion and escaped the back slashes.  So instead of \\s  we had \\\\s.

Once we corrected that it worked.  However we did identify a small challenge.  We think it's with

YacCommit.removeTrailingNewLine

From tortoise on windows the new line is \r\n.   So there is a trailing \r in the comment which forced me to add a (?s) and .* to my expression.  When the comment comes into bitbucket it ends with a \r which failed my expression.  This is by no means major and easily handled in regex.

My apologies for the false alarm here.  You may close this out.

**Comment by sford** [comment]
Thanks for the update, glad you got it sorted out!
