### ISSUE TITLE
YACC Configure button is not available (version 1.6)

### ISSUE THREAD

**Issue by gliptak** [sford/yet-another-commit-checker#120]
I installed version 1.6 from the Marketplace into Stash 3.1.4, which seem to be the latest applicable version as per:

https://marketplace.atlassian.com/plugins/com.isroot.stash.plugin.yacc/versions

but I do not see the YACC Configure button in the Universal Plugin Manager (as described in https://github.com/sford/yet-another-commit-checker/blob/master/README.md) I reviewed various logs to try to see if there was an error, but didn't see anything related.

Was global configuration available in version 1.6 of YACC?

Thanks

**Comment by sford** [comment]
Hi @gliptak ,

Global configuration was [introduced in version 1.7](https://github.com/sford/yet-another-commit-checker/blob/master/CHANGELOG.md), which bumped the minimum required Stash version to 3.5.1. There was some API change or deprecation that required the bump to 3.5.1... I forget exactly what though :-)

**Comment by gliptak** [comment]
@sford Thank you for the pointer. We just have to wait until after an upgrade.
