### ISSUE TITLE
Commit Message Still Regex not working 

### ISSUE THREAD

**Issue by Alonkr** [sford/yet-another-commit-checker#124]
hi i need some help i tring to add some pattern commit that will be with #NNN with description before and after , i am trying this regex on Commit Message Regex : ([A-Z]+-#[0-9][0-9][0-9]+)(.|\n)+
and on the exclide this regex : ^Revert \"|#skipchecks
please help how to do that trick work ? 
exsample commit : 
i have to put this #NNN - it's the number of the issue or defect 
who that will not use it we get commit rejected ..
Issue #856 - Implement CR60 - Add getTelephoneNumberExchangeListoperation to BillerPhone
or this : 
Revert "Issue #858"This reverts commit cbc91fa4b4f4c032febef9020a02bf3f2177c3f3.

**Comment by sford** [comment]
I am not sure I am fully following. that Commit regex, `([A-Z]+-#[0-9][0-9][0-9]+)(.|\n)+` will match messages like:

```
ABC-#123: this is a test
```
because of `[A-Z]+-` in the regex.

However, if you are trying to match `#NNN` or `Issue #NNN`, you will need to fix the regex.

**Comment by Alonkr** [comment]
Allready fixed.

-----Original Message-----
