### ISSUE TITLE
Exclude all Commits on certain branch from checks

### ISSUE THREAD

**Issue by karstenrenhak** [sford/yet-another-commit-checker#129]
Hi,

would it be possible to disable commit checks for a certain branch.

We usually cherry pick a bunch of commits into a releases branch to build a new release. 
Then the check on Jira staus (not closed) denys a push, due to already closed Jira tickets.

Now, it would be helpful to exclude the releases branch from Issue Jql Matcher or any other checks to build a release without changing our deployment process.

Best Regards,
Karsten Renhak

**Comment by sford** [comment]
Hi @karstenrenhak ,

That could be possible. There is already a collection of `Exclude` configuration options... I could imagine a new `Exclude Branch by Regex` setting. You could set it to something like `release/.*` and it could ignore any release branch matching that regex.

**Comment by sford** [comment]
#88 requests this too.

**Comment by sford** [comment]
fixed in #133
