### ISSUE TITLE
Add partial regex match support with find()

### ISSUE THREAD

**Issue by Signus** [sford/yet-another-commit-checker#131]
Add the ability for users to do partial matching, if say they only care about certain components of the message. That way they don't have to account for an entire match of a commit message, branch name, etc. but I find this is most useful in commit messages.

For example, if you manually enter the regex `[A-Z][A-Z_0-9]+\-[0-9]+` for JIRA keys (I know there is a setting for detecting JIRA keys) it will not match a commit with "TEST-123: This is a sample commit message" because [matches()](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#matches()) returns: 

`true if, and only if, a subsequence of the input sequence matches this matcher's pattern`

It in itself is a simple change I can make a PR for, but let me know your opinions:

```java
private List<YaccError> checkCommitMessageRegex(Settings settings, YaccCommit commit) {
    List<YaccError> errors = Lists.newArrayList();

    String regex = settings.getString("commitMessageRegex");
    if(!isNullOrEmpty(regex)) {
        Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE);
        Matcher matcher = pattern.matcher(commit.getMessage());
        
        // We can allow for the configuration of this option
        if (settings.getBoolean("strictCommitMessageRegex", true)) {
            if(!matcher.matches()) {
                errors.add(new YaccError(YaccError.Type.COMMIT_REGEX,
                    "commit message doesn't match regex: " + regex));
            }
        } else {
            if(!matcher.find()) {
                errors.add(new YaccError(YaccError.Type.COMMIT_REGEX,
                    "commit message did not find a partial match for: " + regex));
            }
        }
    }

    return errors;
}
```

**Comment by sford** [comment]
Hi @Signus,

Would it be sufficient for your needs to workaround this by modifying the regex instead of adding a new configuration option? For your example, could you instead use `.*[A-Z][A-Z_0-9]+\-[0-9]+.*`, which I believe would be equivalent to `find()`.

**Comment by Signus** [comment]
That is the workaround I currently utilize, and why I made the suggestion to make a modification to make it simpler for the users to get started using regex more quickly with your add-on.

The other option may simply be to add the option for the user to input a test pattern to validate their pattern with expected input.

**Comment by sford** [comment]
I am a little hesitant adding configuration options for behavior that is already possible. I think the other option of allowing the user to test a pattern would be valuable. Broken regexes are a very common support request, so that would be valuable beyond #131.

**Comment by Signus** [comment]
I will close this then, and likely open a new issue for a feature suggestion for the regex tester (unless it is already planned for the future).

**Comment by sford** [comment]
👍 

I am not planning on personally working on regex tester but feel free to open a feature suggestion (or PR :-) Thanks!
