### ISSUE TITLE
Re: Need Release version of YACC Plugin

### ISSUE THREAD

**Issue by abprakash405** [sford/yet-another-commit-checker#136]
As part of the below ticket, we have tested the beta version of YACC plugin jar that you have provided and it works fine. Could you please provide the RELEASE version of YACC plugin.

We are now in BBS version 4.9.1(UAT and DEV), we have to retest the new YACC on the upgraded version before we move the PROD to 4.9.1 BBS.

Older reference ticket:
https://github.com/sford/yet-another-commit-checker/issues/113

Regards,
Bhanu Prakash A
Barclays

**Comment by abprakash405** [comment]
Could you please update us on this ?

**Comment by sford** [comment]
Yeah, I will get a release out 👍  Thanks for the prodding!

**Comment by abprakash405** [comment]
Could you please let us know, by when can I expect this ? Sorry for chasing, we are near to PROD upgrade, we would like to get this tested by users in the UAT instance of BBS. Thank you !

**Comment by sford** [comment]
1.12 has been released and pushed to marketplace!

**Comment by abprakash405** [comment]
Thanks a lot !

**Comment by sford** [comment]
👍
