### ISSUE TITLE
debugging yacc - how to

### ISSUE THREAD

**Issue by rc-ck** [sford/yet-another-commit-checker#143]
Hi all.

I'm having some issues with yacc misbehaving. It blocks commits to Bitbucket with error "No JIRA Issue found in commit message", while in fact, JIRA issues *are* in commit messages.
So far everything was fine, configs and regexes were not changed, so I'm looking for the cause.

I'd like to look into some logs. Unfortunately, the instructions on enabling yacc logging are not clear enough for me (https://github.com/sford/yet-another-commit-checker#enable-logging). I run curl and then what? Where are the logs? Do I need to download some additional packages? How do I disable the logging when I'm done?

Thanks.

**Comment by sford** [comment]
Hi @rc-ck 

> I run curl and then what? Where are the logs?

The logs will be in the `atlassian-bitbucket.log` log file, which is located in your bitbucket server data directory. I believe the default is somewhere in `/var/atlassian/application-data`, but could be elsewhere depending on how your BBS server is configured.

I should also note that the curl command might need tweaking depending on how your BBS is setup... might need to change `admin` to your admin user, or change hostname or port.

> How do I disable the logging when I'm done?

Log changes done through the BBS REST API are not persistent, so restarting BBS will reset logging to defaults. I haven't tested it, but you can probably reset logging without restarted by changing `debug` to `info` in the URL path... ie... `.../com.isroot/info`.

**Comment by rc-ck** [comment]
@sford thanks for your help, it indeed works as expected. 

Thanks to the access to the logs I've been able to find a bug / logical error in yacc. Normally I'd create another ticket, but this bug also means that there is a security vulnerability in yacc. I think that disclosing it publicly is not the best idea. 

So how can I pass you the details? Via email, maybe?

**Comment by sford** [comment]
@rc-ck For sure, my email address is sdford@gmail.com

**Comment by rc-ck** [comment]
@sford Thanks. Do expect a message soon. In the meanwhile I'm closing this ticket.
