### ISSUE TITLE
Multiline commit message regex fails

### ISSUE THREAD

**Issue by RobSmyth** [sford/yet-another-commit-checker#144]
Hi,

The commit message regex check I'm using works fine for a single line message but fails for a multi-line message. I've tried the `(?s)` prefix and the `(.|\n)*` suffix and neither has any effect. All multi-line commits messages are rejected.

The intent is to ensure that the message starts (first line) with something like "CERN-1234: ". I do not care about following lines. The regex is:

`  .*((Merge)|(((CER[DN]-[0-9]{1,4})|(Maintenance))((/CER[DN]-[0-9]{1,4})*):)).*`

For example a push with a commit message:

`CERN-1234: first line`
`second line`

Is rejected.

Any suggestions?

Rob

**Comment by sford** [comment]
Hi @RobSmyth,

Both `(?s)` and `(.|\n)*` should do the trick. I use this:

```
(?s)([A-Z0-9\-]+): .*
```
This should match your example.

I would suggest simplifying your regex... my guess is that something in there is causing problems. Or, maybe start with my example and then build it up and test one thing at a time.

**Comment by sford** [comment]
You can also try testing your regex with this:

http://www.regexplanet.com/advanced/java/index.html

I prepended `(?s)` to your regex and it matched your multiline example.

**Comment by RobSmyth** [comment]
Thx for looking ... I'll give it another go shortly

**Comment by pwagland** [comment]
I guess that this can probably be closed? I just tried the (?s) prefix on my regex, and it worked like a charm. FWIW, it might be worth putting a hint in the configuration screen to this effect, since it took me a while to find what the issue was.

**Comment by RobSmyth** [comment]
Hi ... yes you can close it now. I've moved on to another team and no longer work with it.

**Comment by sford** [comment]
Will close, thanks for the updates and comments!

**Comment by eddyp** [comment]
This behavior has burnt me today and generated at least 4 man hours of extra work, just because the default is not following the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Also, the exception fields seem to NOT have the same pattern, so this field is also inconsistent in behavior.
