### ISSUE TITLE
Version 1.13 rejects push 

### ISSUE THREAD

**Issue by nicko2n** [sford/yet-another-commit-checker#145]
Hi Sean,

I upgraded to 1.13 of YACC today (from 1.12) and the plugin is now rejecting a push for a commit because of the 'Require Valid JIRA Issue' option on one of our project with key 'TO'

`
remote: Push rejected.
remote:
remote: refs/heads/feature/branch_name: bc982dac9cd3bd59d850d0b97e2cfd1f143c6539: No JIRA Issue found in commit message.
remote:
To ssh://git.diss.local:7999/main/production_scripts.git
`

This is only happening on this project (other are ok), and started after the upgrade. The commit goes through if I disable the option.

**Comment by sford** [comment]
HI @nicko2n ,

YACC 1.14 should fix this. Expect a new release Very Soon™ :-)

**Comment by sford** [comment]
Released!

**Comment by nicko2n** [comment]
Thanks for the quick fix. Deployed and confirmed.
