### ISSUE TITLE
Negative look-around branch regex

### ISSUE THREAD

**Issue by DomhnaillByrne** [sford/yet-another-commit-checker#151]
We're trying to stop direct pushes to certain development branches using a negative look-around regex. 

The regex I'm using is `^(?!(FOO))` which I expect to stop all pushes to any branch beginning with **FOO**. I expect it to allow pushes to branches named **NOT_FOO** etc.. 

So far it does block the branch named **FOO** but also blocks **NOT_FOO**.

> refs/heads/NOT_FOO: Invalid branch name. 'NOT_FOO' does not match regex '^(?!(FOO))'

**Comment by sford** [comment]
I don't have much experience with lookaheads so I can't comment on whether or not the regex is correct. However, the regex should match the entire branch name. So, you might need a .* at the end to match other branches that don't start with FOO.

Try testing `^(?!(FOO)).*` at http://www.regexplanet.com/advanced/java/index.html to see if it does what you want it to.

**Comment by DomhnaillByrne** [comment]
Thank you, yeah the `^(?!(FOO)).*`  solution gives the expected behavior for the plugin. Any regex testers that I'd tried had accepted `^(?!(FOO))` so I was a bit stumped. Thanks for the help.
