### ISSUE TITLE
please post build steps 

### ISSUE THREAD

**Issue by raiello** [sford/yet-another-commit-checker#153]
Could you please post the steps for building your plugin. 
I presume that I start with 
atlas-create-jira-plugin-module

but then which options am I picking? Thanks for your help!

**Comment by raiello** [comment]
Using the Atlas SDK, I was able to build from source using the following steps:
after cloning ...
atlas-cli
and then from the Maven prompt - I ran compile and then package creating the jar

**Comment by sford** [comment]
Yeah, that sounds about right. Try checking out the other `atlas-` commands... you can do stuff like `atlas-package` to package up a jar for install, or `atlas-run` to startup a local BBS server with YACC installed.

**Comment by sford** [comment]
Closing ~ feel free to re-open if you have any other questions.
