### ISSUE TITLE
Commit Rejected due to Message Regex

### ISSUE THREAD

**Issue by edwardtew** [sford/yet-another-commit-checker#154]
I have the following configured in the commit Message Regex to ensure that developers are committing to the correct repo based on the correct JIRA references.
>
> (TAU-[0-9]+)
>
Seen here:
![image](https://cloud.githubusercontent.com/assets/19808346/25319783/68fe1ce8-28f5-11e7-86b9-e20e9dbf4f49.png)

This rejects the push of a commit with the message:

> TAU-147: Implement tags in UITesting.py
> 
> Corrected test scripts to be in line with current master branch
> and updated in accordance with review comments.
>  
 
Snipped from the Atlassian log on the server with debug enabled.

[log-snip.txt](https://github.com/sford/yet-another-commit-checker/files/950257/log-snip.txt)

**Comment by sford** [comment]
@edwardtew: The commit regex needs to match the entire commit message, not just the tag. You might need to add `(.|\n)*` to the end of the regex, or something similar.

**Comment by sford** [comment]
Going to close this ~ feel free to re-open if you have any other questions.

**Comment by bric3** [comment]
Oh my ! I had the regex terminating by `.*` but commits were rejected, allowing `\n` too did the trick. It should be used as an example on the README page.
