### ISSUE TITLE
Update YACC to use new Bitbucket Server 5.0 Hook APIs

### ISSUE THREAD

**Issue by bturner** [sford/yet-another-commit-checker#156]
Bitbucket Server 5.0 includes significant changes to its APIs and SPIs which should greatly simplify the YACC plugin. For example:

* [`Commit`](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/api/reference/com/atlassian/bitbucket/commit/Commit.html) now includes `Person getCommitter()` and `Date getCommitterTimestamp()`
  * This should allow you to scrap your [manual `git rev-list` handling](https://github.com/sford/yet-another-commit-checker/blob/master/src/main/java/com/isroot/stash/plugin/commits/CommitsServiceImpl.java#L66-L75)
* The `GitRefCommandFactory` now includes [`resolveAnnotatedTags`](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/git-api/reference/com/atlassian/bitbucket/scm/git/command/GitRefCommandFactory.html#resolveAnnotatedTags&#40;com.atlassian.bitbucket.repository.Repository,&#32;com.atlassian.bitbucket.scm.git.ref.GitResolveAnnotatedTagsCommandParameters,&#32;com.atlassian.bitbucket.scm.git.ref.GitAnnotatedTagCallback&#41;), which can be passed a set of hashes to access [`GitAnnotatedTag`s](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/git-api/reference/com/atlassian/bitbucket/scm/git/ref/GitAnnotatedTag.html), providing access to the tagger details
  * `GitRefCommandFactory` can be accessed using a simple `component-import`: `<component-import key="gitRefCommandFactory" interface="com.atlassian.bitbucket.scm.git.command.GitRefCommandFactory"/>`
  * This should allow you to scrap your [manual `git-cat-file -p` handling](https://github.com/sford/yet-another-commit-checker/blob/master/src/main/java/com/isroot/stash/plugin/commits/CommitsServiceImpl.java#L56-L64)

Perhaps most importantly, though, Bitbucket Server 5.0 includes a new [`PreRepositoryHook`](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/spi/reference/com/atlassian/bitbucket/hook/repository/PreRepositoryHook.html) which allows add-ons to register a [`PreRepositoryHookCommitCallback`](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/spi/reference/com/atlassian/bitbucket/hook/repository/PreRepositoryHookCommitCallback.html). When registering you can specify [`RepositoryHookCommitFilter.ADDED_TO_REPOSITORY`](https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.0-rc9/spi/reference/com/atlassian/bitbucket/hook/repository/RepositoryHookCommitFilter.html) to indicate only _new-in-repository_ commits should be provided to the callback. Since YACC doesn't need to check commits which are already in the repository, this seems like something that should make the hook easier to implement.

An additional benefit of using our new `PreRepositoryHookCommitCallback` is that the same commits are fed to _every hook_ that registers one. For instances where many `pre-receive`-style hooks are running to do arbitrary validation, this means, instead of every plugin running its own `git rev-list` processes to gather commits, they can be gathered _once_ and fed to every interested add-on. This should result in a meaningful reduction in overhead, if add-on developers migrate to the new SPI.

Please let me know if you have any questions!

P.S. I'll note that Bitbucket Server 5.0 includes its own "Verify Committer" hook which, when enabled for a given repository, validates the committer for new commits, and the tagger for new annotated tags, against the pushing user and rejects the push if the two don't match.
![image](https://cloud.githubusercontent.com/assets/121199/25594676/7ccf7a88-2e76-11e7-9f4c-dc62a0047811.png)

**Comment by bturner** [comment]
I should add that in order to use the new 5.0 API/SPI, you'll need to use AMPS 6.3.0. You can do this with an existing Atlassian SDK by passing `-u 6.3.0` to, for example, `atlas-run-standalone`
```
atlas-run-standalone -u 6.3.0 --product bitbucket --version 5.0.0-rc9 --data-version 5.0.0-rc9
```

That command, for example, will use AMPS 6.3.0 to start 5.0.0-rc9. You'll want your `amps.version` and `bitbucket.version` properties in your `pom.xml`.

**Comment by sford** [comment]
@bturner Thanks for the heads up! Those are some fantastic API changes... I will jump into this soon and start getting YACC updated for testing.

**Comment by sford** [comment]
I started working on this... work in progress PR #159 opened.

So far the new commit callback API is working well and pretty awesome. Really nice not having to drop down to git commands to get the information YACC needs. Code still needs a lot of work, but initial commit checking works 👍

**Comment by sford** [comment]
I pushed up YACC 1.16 that supports BBS 5 using the old deprecated hook API as a quickfix for BBS 5 support. I realized I will need a lot more time to develop and test the new hook API changes.

**Comment by sford** [comment]
@bturner I took a little break on this, but just started working on it again. I got YACC global settings working with the new APIs, which was a little bit of a thorn in my side, but it came together fine once  I got a hook with [`configurable="false"`](https://github.com/sford/yet-another-commit-checker/blob/10028d04831dda6136f66dbf9d9ad8872ecaa0f3/src/main/resources/atlassian-plugin.xml#L73) working.

Couple questions... is the next SDK version going to support AMPS 6.3.0? As far as I can tell, I am running the latest version 6.2.14, which appears to require `atlas-run-standalone -u 6.3.0` to run BBS 5.

Also, I saw that BBS 5.2.0 has support for project hooks.... this is awesome. Do you think you will extend this and add support for global hooks?

**Comment by sford** [comment]
Just merged PR to use new BBS 5 APIs, which removes the need of using the manual git commands. So, should have a huge performance benefit 👍 

This took me forever... it was a fairly significant change and I was worried about breaking existing functionality. I finally bit the bullet and wrote real integration tests by re-introducing jGit (only for tests!) and using it to actually verify that YACC is working as expected and blocking pushes. This gave me a lot more confidence integrating into the new BBS APIs. The YACC code is still a little rough... not happy with everything, but, it should be working.

**Comment by mindsocket** [comment]
Bitbucket PM here :)

Thanks @bturner for raising this, and @sford for putting in the hard work to bring YACC up to date with the 5.x series of APIs! We're pretty excited about the improvements, and I'm sure it will be appreciated by the many teams that use YACC every day.

**Comment by sford** [comment]
@mindsocket  👍 

I just released YACC 1.17 with these performance enhancements. Closing this out.

**Comment by sford** [comment]
@bturner If you have some time, could you spot check my [annotated tag code](https://github.com/sford/yet-another-commit-checker/blob/yacc-1.17/src/main/java/com/isroot/stash/plugin/YaccServiceImpl.java#L150-L173) to see if I am using the `resolveAnnotatedTags` API correctly?

As far as I understand it, I pass it a tag RefChange and it will call the callback with annotated tags, if any. I am currently trying to reproduce #166... an IllegalStateException is being thrown by AbstractBatchCatFileHandler ~ trying to figure out if I am using the API wrong.

**Comment by bturner** [comment]
@sford The structure of the request looks fine to me. One thing I'd tweak is to call `messageMessageLength(0)` on the `GitResolveAnnotatedTagsCommandParameters.Builder` before you `build()` it. You don't use the message, as far as I can see, so not asking for it will make your request more efficient. (Without that call, by default tag messages will be provided to you regardless of their length.)
