### ISSUE TITLE
Clear-view about yet-another-commit-checker

### ISSUE THREAD

**Issue by Nagaarjun2794** [sford/yet-another-commit-checker#160]
Hi Team,

1. Why this plugin is not supported by atlassian.
2. What are the bugs ,still exist in this plugin.
3. Give a detailed explanation about the plugin.

Regards,
Nagaarjun

**Comment by sford** [comment]
Hi Nagaarjun,

The plugin is not supported by Atlassian because they didn't create it. If you find any bugs, let me know :-) Detailed explanation can be found [here](https://marketplace.atlassian.com/plugins/com.isroot.stash.plugin.yacc/server/overview).
