### ISSUE TITLE
Inconsistent platforms in release documentation

### ISSUE THREAD

**Issue by wurp** [sford/yet-another-commit-checker#161]
https://marketplace.atlassian.com/plugins/com.isroot.stash.plugin.yacc/server/overview mentions Stash but not Bitbucket.

https://marketplace.atlassian.com/plugins/com.isroot.stash.plugin.yacc/server/versionhistory mentions Bitbucket but not Stash.

Can you make the documentation consistent? It seems as if this plugin is for Bitbucket, not Stash.

**Comment by sford** [comment]
Fixed! Thanks for the heads up!
