### ISSUE TITLE
YACC is blocking all commits

### ISSUE THREAD

**Issue by karstenrenhak** [sford/yet-another-commit-checker#164]
When I activate YACC on any repository all commits are rejected with such a message:

> pre-receive hook declined
> Hook com.isroot.stash.plugin.YaccHook failed. Error: 
> Commit 'd21a0780cc968f6b3469e2e20cdb51150b68bb2b' does not exist in repository 'isi-app'.

According the the YACC configuration this commit should pass the hook.

The given commit id from this message is the commit id from the new commit which I tried to push.
The git push was sent from an eclipse Neon.3 
> Git integration for Eclipse	4.7.0.201704051617-r	org.eclipse.egit.feature.group	Eclipse EGit
> Java implementation of Git	4.7.0.201704051617-r	org.eclipse.jgit.feature.group	Eclipse JGit

Here is the corresponding error log from the bitbucket server:
> 2017-07-27 10:38:33,374 WARN  [threadpool:thread-1] kre @1QIIJATx638x136x0 192.168.203.187 "POST /scm/isi/isi-app.git/git-receive-pack HTTP/1.1" c.a.s.i.h.r.PreReceiveRepositoryHookAdapter Receive Hook com.isroot.stash.plugin.YaccHook failed. 
> com.atlassian.bitbucket.commit.NoSuchCommitException: Commit 'd21a0780cc968f6b3469e2e20cdb51150b68bb2b' does not exist in repository 'isi-app'. 
>        at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.newNoSuchCommitException(GitCommandExitHandler.java:167) ~[na:na] 
>        at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.evaluateStdErr(GitCommandExitHandler.java:70) ~[na:na] 
>        at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:197) ~[na:na] 
>        at com.atlassian.bitbucket.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:31) ~[bitbucket-spi-4.9.1.jar:na] 
>        at com.atlassian.bitbucket.scm.BaseCommand.callExitHandler(BaseCommand.java:146) ~[bitbucket-spi-4.9.1.jar:na] 
>        at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:272) ~[bitbucket-spi-4.9.1.jar:na] 
>        at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.get(BaseCommand.java:241) ~[bitbucket-spi-4.9.1.jar:na] 
>        at com.atlassian.bitbucket.scm.BaseCommand.call(BaseCommand.java:83) ~[bitbucket-spi-4.9.1.jar:na] 
>        at com.isroot.stash.plugin.commits.CommitsServiceImpl.getNewCommits(CommitsServiceImpl.java:71) ~[na:na] 
>        at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:57) ~[na:na] 
>        at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70) ~[na:na] 

Bitbucket Version: 4.9.1 
Git Version: 2.11.1 
Yet Another Commit Checker plugin for Atlassian Bitbucket Server: 1.15 

At the moment I have no idea about the reason of this strange behavior.

**Comment by sford** [comment]
Hi @karstenrenhak,

I believe you are using an incompatible version of git with BitBucket. See [BSERV-9388](https://jira.atlassian.com/browse/BSERV-9388). Changes in Git 2.11 interfere with hook functionality in BBS  <4.13. I would try either downgrading git or updating to the latest BBS version.

**Comment by karstenrenhak** [comment]
Thanks for the prompt answer.
It looks like that there is no easy or fast solution. I have to discuss possible options with our administrators.

Feel free to close this issue.

**Comment by sford** [comment]
👍
