### ISSUE TITLE
Allow configuration at project level level (only global & repository configuration are currently available)

### ISSUE THREAD

**Issue by ldellouve** [sford/yet-another-commit-checker#165]
Hi,

With the 5.2 version of bibucket, it's possible to configure plugins at project level (see: release notes https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-2-release-notes-917966093.html & attached file:
![image](https://user-images.githubusercontent.com/5902539/28959973-14627d66-78fd-11e7-9676-b069d4bbcee5.png)
It will improve the plugin to make the configuration possible at project level,

Sincerely

**Comment by sford** [comment]
Yeah, on my radar! 👍

**Comment by AlexanderAmelkin** [comment]
Need that a lot! I have over a dozen repos in a project, and having to configure yacc for each of them separately is a maintenance nightmare! I'd give this issue top priority.

**Comment by coshea** [comment]
This would be very helpful for me!

**Comment by calfzhou** [comment]
really need this feature. is there any progress on it?

**Comment by ClemGrs** [comment]
Hi! 

Yes it would very helpful, it is not comfortable to editing one by one each repository.

You do an excellent Job with this plug-in, thanks a lot.

**Comment by sford** [comment]
Released in YACC 1.21 🎉
