### ISSUE TITLE
About bulk edit the hook setting

### ISSUE THREAD

**Issue by kaku0315** [sford/yet-another-commit-checker#171]
I am sorry I want to ask if you can tell me this hook's data are stored in which one database's table?

Because we want to bulk modify the settings for multiple Repositories.

But in the interface does not seem to be able to achieve.

So we want to try from the direction of modifying the database.

Thank you & Bother you,
Kaku

**Comment by sford** [comment]
Hi Kaku, not a bother at all!

I don’t know the BBS database schema on top of my head, so I don’t know what table settings are stored. YACC stores settings using the BBS plugin interface, so YACC doesn’t touch the database itself directly. It is all up to BBS to store the settings using its own schema. 

If you want to configure a lot of repositories, I recommend checking out the BBS Rest API: https://developer.atlassian.com/static/rest/bitbucket-server/latest/bitbucket-rest.html

The rest API allows you to enabled and configure hook plugins such as YACC. This can be automated to configure all your repositories. This would be more reliable than touching the database directly.

**Comment by george-vulov** [comment]
Here's the relevant documentation page: [How to modify YACC settings programmatically](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1484652654/How+to+modify+YACC+settings+programmatically).
