### ISSUE TITLE
How can I set a repository to go back to using global settings after first customing repo settings?

### ISSUE THREAD

**Issue by nathanbedford** [sford/yet-another-commit-checker#175]
Here's my scenario:

We've got yacc global settings set the way we like them.  Maybe I want to test new settings just on one repo, so I go that repo's settings page, then enable yacc via the 'hooks' page.  I test my new settings here, but when I'm done testing these settings, I want to have that repo go back to using the global settings.

I assumed/hoped I could just set the hook for that repo back to 'Disabled', and yacc would start using the global settings again, but that doesn't seem to be the case. Now that repo acts as if yacc is totally disabled, and all my commit messages are accepted.

Is there something I missing, or some other way to make that repo use the global settings again?

**Comment by nathanbedford** [comment]
After a bit of poking around it looks like this line of code is responsible for this behavior:
https://github.com/sford/yet-another-commit-checker/blob/master/src/main/java/com/isroot/stash/plugin/YaccGlobalHook.java#L61

Specifically, it seems that after I've enabled and used a repo hook, it gets set to a 'configured' state, and I don't know how to un-configure it.  So `hook.isConfigured()` is returning true always after enabling a repo once. I've confirmed this locally.

I know in my case, I'd prefer to see yacc go back to the default settings if the repo hook is disabled, regardless of 'configured' status.  @sford, thoughts?

**Comment by sford** [comment]
I have a potential fix in PR #176 ... I think it is as simple as removing the configured check and only relying on enabled. I am not positive why it was checking 'configured' because it doesn't really make sense to me... I might need to do a little more testing on it.

**Comment by nathanbedford** [comment]
Thanks @sford! Let me know if I can help in any way (beta testing, moral support, whatever) :-)

**Comment by philipooo** [comment]
Hi @sford 
Any plans when this bugfix will be released?

**Comment by sford** [comment]
@nathanbedford , @philipooo:

I just released YACC 1.19 that fixes global settings after repo hook has been enabled/disabled. Can you give it a try and let me know if all is well? Thanks!

**Comment by nathanbedford** [comment]
Thanks @sford , will do

**Comment by nathanbedford** [comment]
I just tried v1.19 in our sandbox environment, and it's working the way I'd expect it to now :) Thanks for the quick fix.

**Comment by sford** [comment]
Thanks for checking!
