### ISSUE TITLE
Global Branch Name Regex does not work

### ISSUE THREAD

**Issue by philipooo** [sford/yet-another-commit-checker#180]
I tried to configure a global Branch Name Regex **^[A-Za-z0-9-/_]+$** to prevent branch names with chars other than the specified. Repo YACC hooks ist disabled. But it seems like the Regex is not beeing executed. When I configure the Branch Name Regex on the repository directly it works.

Facts:
- YACC 1.18
- Bitbucket Server 5.6.2

Btw: Awesome plugin! Thank you very much.

Cheers Philip

**Comment by philipooo** [comment]
In one of our repositories it seems to work. Maybe this relates to #175 ?

**Comment by sford** [comment]
Hi @philipooo ,

Yeah, there is a high chance that it is related to #175... the issue you described can be explained by it.

**Comment by philipooo** [comment]
#175 solved the problem! Thank you very much.
