### ISSUE TITLE
Functionality Question about YACC

### ISSUE THREAD

**Issue by naga1023** [sford/yet-another-commit-checker#185]
I have been using YACC in my BitBucket server. The functionality I would like to be implemented is Changing the status of the Jira ticket when ever a pull request happens in the BitBucket. 

Currently I am using JiraSoftware Cloud and BitBucket server, I have tried this functionality using the Jira Triggers, but triggers are not working may be because of the Cloud-Server environment. 

So, just want to know if this can be achieved by YACC. It would be great if I have all my functionalities work from a same plugin. 

.

**Comment by sford** [comment]
Hi @naga1023 , that currently isn't possible with YACC. YACC is pretty focused on checking commits. It isn't really intended to drive JIRA workflows based on actions in BitBucket sever.

**Comment by naga1023** [comment]
Thanks for the response. Appreciate your work.
