### ISSUE TITLE
YaccServiceImpl.checkCommitMessageRegex should find matches in the presence of line separators

### ISSUE THREAD

**Issue by t101jv** [sford/yet-another-commit-checker#187]
I added the following test to YaccServiceImplTests and it fails. Is this expected behavior? Fixing it is not as simple as changing the if test from `!matcher.matches()` to `!matcher.finds()` as this caused three new test failures.
```java
@Test
public void testCheckCommit_commitMessageRegex_commitMessageHasNewlineMatches()
        throws Exception {
    settings.setCommitMessageRegex("[a-z ]+");
    when(jiraService.doesJiraApplicationLinkExist()).thenReturn(true);

    YaccCommit commit = mockCommit();
    when(commit.getMessage()).thenReturn("matches" + System.lineSeparator() + "regex");

    List<YaccError> errors = yaccService.checkCommit(settings, commit, null);
    assertThat(errors).isEmpty();
}
```

**Comment by sford** [comment]
Hi @t101jv ,

Thanks for including the test case!

> Is this expected behavior?

Yes, using the regex `[a-z ]+`, that is expected. It is matching a space, which doesn't include line separator.

You can instead try using a regex like `[a-z\\s]+`. That would match a-z, plus whitespace like spaces and line separators. That test case passes after using this regex.

**Comment by t101jv** [comment]
What i ended up doing was using a oneline regex bracketed by (.|\\R)* to glob up other lines
