### ISSUE TITLE
YACC is not allowing to push existing branches which are not in line with Branch Regex

### ISSUE THREAD

**Issue by AkulB** [sford/yet-another-commit-checker#192]
I am using,

Bitbucket Server 4.13.0
YACC 1.11
Git version on server 2.10
Git client version git version 2.16.2.windows.1

I have applied this regex at repo level, ^[a-z0-9_\/\.\-]+$
It is working as expected for new branches. But, it is also blocking the existing branches which do not match this regex. I believe this should not be the case as per the following statement from page https://github.com/sford/yet-another-commit-checker,

**If present, only branches with names that match this regex will be allowed to be created. This also affects branches created within the Bitbucket Server UI. This only affects new branches, existing branches that don't match this regex will still be allowed.**

**Error Message for existing branch,**
$ git push origin phase7Fixes
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 353 bytes | 353.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote:
remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)
remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \
remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
remote:    || E ||      || R ||      || R ||      || O ||      || R ||
remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'
remote:
remote:
remote: Push rejected.
remote:
remote: refs/heads/phase7Fixes: Invalid branch name. 'phase7Fixes' does not match regex '^[a-z0-9_\/\.\-]+$'
remote:
remote:     The branch name is not in sync with the branch naming standards.
remote:
To ssh://testbitbucket.int.xxx.com:7999/tool/bitbucket.git
 ! [remote rejected] phase7Fixes -> phase7Fixes (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@testbitbucket.int.xxx.com:7999/tool/bitbucket.git'

**Comment by sford** [comment]
Hi @AkulB, YACC 1.11 is pretty old. Upgrading YACC should fix the issue your are running into. Fix PR is #130 and released in YACC 1.12.

**Comment by sford** [comment]
Going to close this as fixed because upgrading YACC should fix it. If you have any other questions, let me know.

**Comment by AkulB** [comment]
I am sure the upgrade would fix it.
Could you please confirm if these go well together,
BB 4.13.0
Git 2.10
YACC 1.15

If so, I am planning to upgrade YACC from 1.11 to 1.15 and try out the new features and fixes? Also, in a couple of months I would be upgrading BB to 5.13 and YACC to 1.19.

**Comment by sford** [comment]
Yeah, the version combination should work fine. 👍

**Comment by bturner** [comment]
@sford can confirm, but you should _not_ need to upgrade Git on the server prior to upgrading YACC; the plugin should work fine with the version of Git you already have. YACC 1.13+ _support_ Git 2.11+, but they do not _require_ it.

I'm not sure about a maintenance window; it seems like only you can decide that. The plugin upgrade itself can absolutely be done with the server online and no downtime. It should take just a few seconds for Bitbucket Server to disable the existing one and enable the new one.

All of your YACC settings should remain the same without any need for reconfiguration. The settings are persisted in Bitbucket Server and they're not tied to the plugin version. (That said, there _are_ changes a plugin developer can make that will result in "losing" their settings, but as far as I'm aware nothing like that has happened with YACC.)

**Comment by AkulB** [comment]
Thanks, @bturner for your prompt reply!
@sford  Can you please confirm what turnor has suggested.

**Comment by AkulB** [comment]
Awesome!
In a couple of months, my upcoming versions are going to be
BB 5.13
GIT 2.18.0
YACC 1.19

Hope they will go together..

**Comment by AkulB** [comment]
@sford  @bturner 
Can you guys please point me to the rollback steps? In case anything goes wrong on production, I want the handy steps to roll back the version of YACC to 1.11 asap w/o any impact on end users or downtime.

**Comment by sford** [comment]
@AkulB,

To rollback, you can [download whatever version of YACC you need from Atlassian Marketplace](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker/version-history), and then upload the jar directly to BitBucket Server using its plugin manager.

**Comment by AkulB** [comment]
Thanks, @sford 
I tried installing 1.11 this way. But,

**I had to uninstall 1.15 before uploading 1.11 successfully.**

When I tried installing 1.11 w/o uninstalling 1.15, the installation process showed success but the version was still 1.15 everytime. Can you please confirm if uninstalling 1.15 is the right way to go and won't hurt the yacc configurations (globally, repo, and fork) those already exist in bitbucket.

This is my rollback process and has to be solid enough!

**Comment by bturner** [comment]
@AkulB Correct. You can't downgrade by installing an old version over a newer one because Atlassian Plugins always enables the newest version of a given plugin. That means you need to uninstall any newer version(s) before reinstalling the old version. (Note that the _installation_ of 1.11 is successful; it's "just" not enabled. A nuanced distinction, I'd readily agree, but it's how it works, for better or worse.)
