### ISSUE TITLE
Unable to redefine "Require Valid JIRA Issue(s)" error message

### ISSUE THREAD

**Issue by MagicPush** [sford/yet-another-commit-checker#198]
YACC v1.19

There is "Error Message Customization" section in the plugin configuration.
But there is no option to redefine "Require Valid JIRA Issue(s)" error message.

**Comment by crazy-max** [comment]
@MagicPush @sford PR #210 should be ok ?

**Comment by sford** [comment]
Hi @crazy-max , thanks for the PR! Give me some time to checkout and test. Thanks again! 👍

**Comment by sford** [comment]
PR merged. Will go up in next release.

**Comment by MagicPush** [comment]
@crazy-max , @sford thank you!
