### ISSUE TITLE
Question: Possible to block all commits to repository remotely ie. using some string in commit message?

### ISSUE THREAD

**Issue by petripanula** [sford/yet-another-commit-checker#211]
Just looking a possibility to block all commits to Bitbucket repository from Jenkins for example if some job fails there. Was thinking that one possible solution would be to enable some pre hook via commit message.. Or any other solutions?

Thanks
-Pete

**Comment by sford** [comment]
Hi @petripanula ,

I think this is a bit out of scope for YACC, but yes, it is theoretically possible to create some sort of hook to block a push depending on CI builds.
