### ISSUE TITLE
Is Branch Name Regex supported for old Bitbucket server ? (4.14.5)

### ISSUE THREAD

**Issue by jintoppy** [sford/yet-another-commit-checker#215]
Our bitbucket server is currently on 4.14.5 version. We would like to install YACC for doing Branch Name Regex. Which YACC version is supported for Bitbucket server 4.14.5 and does that versoin supports Branch Name Regex?

**Comment by sford** [comment]
Hi @jintoppy , here is YACC release history:
https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker/version-history

YACC 1.15 is the last release to support 4.x. It has branch name regex.
