### ISSUE TITLE
Facing issue when trying to push changes (pre-receive hook declined)

### ISSUE THREAD

**Issue by POOJANAN** [sford/yet-another-commit-checker#217]
Hello,
I am using version 1.14 ,I am facing issue whenever I tried to push my changes in master repository.
error message from Git:---->
remote: Hook com.isroot.stash.plugin.YaccHook failed. Error:
remote: Commit 'dc760784850b212677cd957675623e357e9ff860' does not exist in repository 'rep_1'.
To ssh://auuw03vp5003:7999/project_1/rep_1.git
 ! [remote rejected] project_1 -> project_1 (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@auuw03vp5003:7999/project_1/rep_1.git'

**Comment by sford** [comment]
What version of BBS and git are you using?

This feels suspiciously like git compatibility issues described in #139.

**Comment by POOJANAN** [comment]
I am using BBS - 4.9.1v and Git of 2.15v
I reffered #164 ,which is similar to my issue .
Its most probably compatibility issue.
Thank you for your response.

**Comment by sford** [comment]
Yes, it is most likely compatibility issues with unsupported version combinations. Especially with git >=2.11 and BBS 4.x as described in #164. git 2.15 wasn't officially supported until BBS 5.x.

You will need to figure out how to get onto supported version combinations for BBS and git.
