### ISSUE TITLE
YACC does not like my last name

### ISSUE THREAD

**Issue by ivanelson** [sford/yet-another-commit-checker#218]
Hi,

YACC is rejecting my push:

> remote: refs/heads/develop: 0712b0e93edfa266861f21d8b4945bf08cb81045: expected committer name 'Sergio Sousa' but found 'sergio'

This is the commit in question:

> commit 9e39be7cd67c97bfbe6c3880833cba7f79cee7c6
> Author:     Sergio Sousa <sergio.sousa@band.com>
> AuthorDate: Tue May 28 19:20:48 2019 -0300
> Commit:     Sergio Sousa <sergio.sousa@band.com>
> CommitDate: Tue May 28 19:20:48 2019 -0300
> 

See the name "sergio" in tiny in the rejection message. However, there is no "sergio" in my configuration. Where is YACC getting the same value "sergio"?

When I change my last name from: Sousa to: Other(Any name other than Sousa)

> git config user.name 'Sergio OtherName'
> git config user.email 'sergio.sousa@band.com'
> git commit --amend --reset-author
> git push origin develop

Here's what happens:

> remote: refs/heads/develop: f922b2cfffe0eab4f4238e2e547d1edaf5aff46c: expected committer name 'Sergio Sousa' but found 'Sergio OtherName'

The rejection message changes and shows the value set in git (OtherName).

But if I go back to "Sergio Sousa":
> remote: refs/heads/develop: c71a4b0756f7e2470e4ff97217992f1770ef4782: expected committer name 'Sergio Sousa' but found 'sergio'

I tried it [here](https://github.com/sford/yet-another-commit-checker#yacc-is-rejecting-my-push-complaining-that-my-user-name-andor-email-is-wrong-but-the-author-from-git-log-is-correct) and it did not work.

Any suggestion? How can I debug this?

- git version 2.7.4
- Atlassian Bitbucket v6.3.0

Grateful

**Comment by sford** [comment]
> Where is YACC getting the same value "sergio"?

In the context of the `expected committer name 'Sergio Sousa' but found 'sergio'` message, sergio should be from [BBS Commit.getCommiter().getName()](https://docs.atlassian.com/bitbucket-server/javadoc/6.3.0/api/reference/com/atlassian/bitbucket/commit/Commit.html#getCommitter()).

What does cat-file return for `c71a4b0756f7e2470e4ff97217992f1770ef4782`?

```
git cat-file -p c71a4b0756f7e2470e4ff97217992f1770ef4782
```

What what its worth, in the first example above, YACC is checking `0712b0e93edfa266861f21d8b4945bf08cb81045` but the example commit in question you give is `9e39be7cd67c97bfbe6c3880833cba7f79cee7c6`... which is a different commit. Might not change anything but maybe double check the commit refs to make sure you are looking at the right commit.

**Comment by ivanelson** [comment]
> > Where is YACC getting the same value "sergio"?
> 
> In the context of the `expected committer name 'Sergio Sousa' but found 'sergio'` message, sergio should be from [BBS Commit.getCommiter().getName()](https://docs.atlassian.com/bitbucket-server/javadoc/6.3.0/api/reference/com/atlassian/bitbucket/commit/Commit.html#getCommitter()).
> 
> What does cat-file return for `c71a4b0756f7e2470e4ff97217992f1770ef4782`?
> 
> ```
> git cat-file -p c71a4b0756f7e2470e4ff97217992f1770ef4782
> ```
> 
> What what its worth, in the first example above, YACC is checking `0712b0e93edfa266861f21d8b4945bf08cb81045` but the example commit in question you give is `9e39be7cd67c97bfbe6c3880833cba7f79cee7c6`... which is a different commit. Might not change anything but maybe double check the commit refs to make sure you are looking at the right commit.

Sorry! I pasted the wrong commits, disregard.

Let's admit these commits:

> remote: refs/heads/develop: bb0bb69943d679cb4999cca09dcfbebf7408b7c7: expected committer name 'Sergio Sousa' but found 'sergio'

> git cat-file -p bb0bb69943d6
> tree 717b6d3d459c82c81c3b93f4c0cf7fc014ae0507
> parent 2458e45110acb4ff768a1c0cfb271592b7e11800
> author Sergio Sousa <sergio.sousa@band.com> 1559093793 -0300
> committer Sergio Sousa <sergio.sousa@band.com> 1559093793 -0300

**Comment by sford** [comment]
@ivanelson I don't see anything immediately obvious. `sergio` should be pulled from commit by Bitbucket Server. The fact that the only place `sergio` appears in bb0bb699 is the email is sort of odd.

Couple questions...

1. Are you using a supported version of git on BBS server? (ie, could this be a git bug?)
2. Not sure this is even possible, but is there some sort of `.mailmap` in the repo that might be translating names before hitting BBS?

**Comment by ivanelson** [comment]
> @ivanelson I don't see anything immediately obvious. `sergio` should be pulled from commit by Bitbucket Server. The fact that the only place `sergio` appears in bb0bb699 is the email is sort of odd.
> 
> Couple questions...
> 
> 1. Are you using a supported version of git on BBS server? (ie, could this be a git bug?)
> 2. Not sure this is even possible, but is there some sort of `.mailmap` in the repo that might be translating names before hitting BBS?

You're right! The mailmap was replacing the value. 

Grateful
