### ISSUE TITLE
Commit message and file content checks when editing a file in the browser doesn´t work

### ISSUE THREAD

**Issue by bck2fe** [sford/yet-another-commit-checker#222]
There is a missing feature inside of the Bitbucket API, see https://jira.atlassian.com/browse/BSERV-9521
Please update the YACC if the feature (API) is available.

**Comment by CathySoMcK** [comment]
Yes please.  My power users are clamoring to be able to use the API for edits...

**Comment by sford** [comment]
#140 for commit message for browser file edit
