### ISSUE TITLE
Plugin does not work with Bitbucket online editor

### ISSUE THREAD

**Issue by gaurav1264** [sford/yet-another-commit-checker#228]
Hi,

YACC plugin does not reject the push if commits are done using Bitbucket online editor. I am using Bitbucket v5.15.2 datacenter edition which has edit functionality in browser and commit the change. 

YACC plugin version is v1.24 datacenter

Ideally, YACC pre-commit hook should restrict the push if configured validation fails.

**Steps to reproduce the issue:**
- Repository is configured with YACC settings as "(DTSDEV-\d+)|(ECTL-\d+) .*" in commit message regex
- Edit any file online and commit without any JIRA id
- Commit should fail stating YACC validation error

Please let me know if any details required.

**Comment by gaurav1264** [comment]
I see browser file edit feature's work in progress in https://github.com/sford/yet-another-commit-checker/pull/226. Lets wait for the release. 

Let me know if I can help in testing

**Comment by sford** [comment]
@gaurav1264 If you are still interested in helping with testing, 1.25 SNAPSHOT file edit commit message checking is available here:
https://github.com/sford/yet-another-commit-checker/actions/runs/36750102

Jar can be uploaded in BBS plugin manager to update YACC.

**Comment by sford** [comment]
In meantime, going to close this as duplicate in favor of #140.

**Comment by gaurav1264** [comment]
Hi @sford , I have tested the plugin v1.25-SNAPSHOT and works with in-line browser edit. Thanks.

**Comment by sford** [comment]
@gaurav1264 , thanks for spot checking!

> When are you planning to release v1.25 for General Availability (GA)?

No date planned yet. Is everything working like you would expect?

**Comment by gaurav1264** [comment]
Yes, for me, everything is working as expected. Following are the testing scenarios was performed:

- Git push should fail when there is no Jira id mentioned in commit message + Using git bash
- Should push the commits if valid JIRA id mentioned in commit message + Using git bash
- Git push should fail when there is no Jira id mentioned in commit message + Using online editor
- Jira Issue Key validation against Jira Instance
- JQL Validation

Did I miss anything to test? I need expert help :)

Do you have plan to add more features/ bug fix in the v1.25? If not, then plugin can be release for GA.

**Comment by bharathnatarajan1** [comment]
@sford I work with @gaurav1264 and have tested following features and ensured it works using YACC 1.25-SNAPSHOT jar in our BitBucket Environment:

1) Online edit commit message validation
2) Commit message validation when code 'push' from Git Client to remote repository
3) Commit message Jira Issue Key validation using Regex when code 'push' from Git Client to remote repository
4) Issue JQL Matcher validation

It would be good to see the latest version of plug-in in Atlassian Market place, so that we can adopt it in our BitBucket environments.

**Comment by bharathnatarajan1** [comment]
@sford  Could you please let us know when we can expect YACC 1.25 release version? Do you have date for release of this version in Atlassian Market Place(https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker)
