### ISSUE TITLE
Bitbucket Server 7.0 support

### ISSUE THREAD

**Issue by fourofspades** [sford/yet-another-commit-checker#238]
Is there much work to support the changed APIs?

This is now the only plug in that's marked as incompatible for us, and there are some tasty improvements in pull requests in Stash 7

**Comment by sford** [comment]
Agreed... very tasty :-) BBS 7 looks to have _just_ been released. I don't suspect many changes are needed, but support for BBS 7 is incoming.

**Comment by sford** [comment]
@fourofspades Version requirements updated ~ should be good to go. Integration tests pass in BBS 7 👍

**Comment by fourofspades** [comment]
Been running with released version of YACC and bitbucket 7.0.x for several weeks now, no probems.
