### ISSUE TITLE
YACC Plugin API Details

### ISSUE THREAD

**Issue by sumanth82** [sford/yet-another-commit-checker#244]
Hi,

I'm trying to enable and update the YACC Plugin, settings via API and doesn't seem to work well. Is there any better documentation for this? 

I'm following this doc:
https://docs.atlassian.com/bitbucket-server/rest/7.2.3/bitbucket-rest.html#idp363

Atlassian Bitbucket - v5.9.1 is used

Doesn't work with this - /rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/settings/hooks/{hookKey}/enabled

or this:

/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/settings/hooks/{hookKey}/settings

**Error:**

***
{'errors': [{'context': None, 'message': 'The settings must only have values of type String, Boolean or Number.', 'exceptionName': None}]}
*** 

**API:**

***

branch_repo_url = "https://stash.com/rest/api/1.0/projects/PR104043/repos/test123/settings/hooks/com.isroot.stash.plugin.yacc:yaccHook/settings/"

r=requests.put(branch_repo_url, json={"details": { "key": "com.isroot.stash.plugin.yacc:yaccHook", "name": "Yet Another Commit Checker", "type": "PRE_RECEIVE", "description": "Yet Another Commit Checker pre-receive hook.", "version": "1.18.2-10", "configFormKey": "com.isroot.stash.plugin.yacc:yaccHook-config-form", "scopeTypes": [ "REPOSITORY" ] }, "enabled": True, "configured": True, "scope": { "resourceId": 4, "type": "REPOSITORY" } }, auth=(username,password))
json_response=r.json()
print(json_response)

***

Thanks

**Comment by sford** [comment]
@sumanth82 Looks like you are getting validation errors? 

YACC has an extensive test suite that uses the BBS API to configure settings and enable/disable plugin. Here is how it usees `/enabled` api:
https://github.com/sford/yet-another-commit-checker/blob/master/src/test/java/it/com/isroot/stash/plugin/util/BitbucketServerRestClient.java#L77-L90

Just a simple PUT on `/enabled`.

Regarding the python snippet, it doesn't look like the correct settings JSON object is being passed to it. Here is example of settings update that YACC does in its test:
https://github.com/sford/yet-another-commit-checker/blob/master/src/test/java/it/com/isroot/stash/plugin/CommitterNameTest.java#L26

Settings object looks like `{"requireMatchingAuthorName": "true"}`

**Comment by sumanth82** [comment]
Thanks @sford . This was super helpful. 

As you mentioned, here is what works

***

branch_repo_url = "https://stash.com/rest/api/1.0/projects/PR104043/repos/test123/settings/hooks/com.isroot.stash.plugin.yacc:yaccHook/enabled/"

r=requests.put(branch_repo_url, json={"boolean-value": True, 'requireMatchingAuthorName': True, 'requireMatchingAuthorEmail': True}, auth=(username,password))

***
