### ISSUE TITLE
Default settings, enforce to all repostories

### ISSUE THREAD

**Issue by PeterSawyer** [sford/yet-another-commit-checker#45]
Is there a way that we can make commit checker be on by default for existing and or new repositories.  

Have often found a new repository is when the rules are broken.  We need to enforce it.

We also have 100's of repositories so a global setting or macro would be most useful in setting it up.

Regards
Peter

**Comment by sford** [comment]
Hi Peter,
 
YACC is implemented as a per-repository hook. I am not familiar with how to auto-enable it for new repositories (not sure it is possible?), and adding global settings would be non-trivial.

However, have you looked into the Stash REST API? It allows you to enable and configure plugins. 
Check out https://developer.atlassian.com/static/rest/stash/3.7.1/stash-rest.html#idp3182624 for how to do this.

Using the REST API, you could audit and/or configure YACC for all your repositories. Maybe even add it to a cron job that periodically makes sure new repositories have YACC enabled with the correct settings.

**Comment by PeterSawyer** [comment]
Thanks, I will get familiar with the API and implement this as an hourly repo iterate check apply process.

**Comment by george-vulov** [comment]
Here's some relevant documentation on how to enable YACC via the REST API: [How to modify YACC settings programmatically](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1484652654/How+to+modify+YACC+settings+programmatically).
