### ISSUE TITLE
Reject commits base on diff contents.

### ISSUE THREAD

**Issue by chillitom** [sford/yet-another-commit-checker#46]
Would love to be able to reject commits based on the content of commits.. for example if the diff contains the string "NO-COMMIT" then reject the commit.

Would this be hard to implement?

**Comment by sford** [comment]
Could you achieve the same behavior by adding a commit message that violates the commit regex? Just wondering, what is your use-case?

**Comment by chillitom** [comment]
Use case is that you make a temporary change (e.g remove checks or change constants or override permissions) whilst experimenting/debugging in the code base but want to be sure that change never makes it to production. A commit message check is no good as you have to remember that the modification is there, if you remember you may as well remove it.  Idea would be to be able to drop a comment next to the change e.g. "// NO-COMMIT" and be sure you can't push it to production.

**Comment by sford** [comment]
Thanks for the clarification. It is unlikely for YACC to support that. Content diffs aren't trivial to obtain, and protecting production is better solved by a CI server (such as Jenkins, Travis CI, Bamboo, etc). A CI server will ensure that the actual code meets sufficient quality standards before hitting production. For instance, ensuring that all tests are passing, static analysis tools pass, or that there are no TODO/FIXME/etc comments to prevent in-progress code from hitting production.
