### ISSUE TITLE
The plugin reject a push on multi-lines comment

### ISSUE THREAD

**Issue by ctsyeh** [sford/yet-another-commit-checker#47]
We have two developers who couldn't push their commits to the central repository.  We reviewed and updated their check-ins comment with git rebase command and verified that the comment passes the RegExp validation but then we realized that some commits contain multi-line commends.  Once we merged the line, the push was successful.  

Is it possible to update the plugin to support Multi-lines comments.

**Comment by sford** [comment]
Hey @ctsyeh, could you provide a sample multiple line commit message and the regex you are currently using that is rejecting it?

**Comment by ctsyeh** [comment]
Hi Sean,

Thanks for the quick response.  See below.  I have never run into this issue myself since I use the command-line and only enter one line commit comment.  However, our developers are using Atlassian SourceTree and it has a textbox for check-in comment, so they paste in multi-lines.

Also, if you simply type git commit without “-m”, it will bring up an editor which you can enter multi-lines.

Below are 3 commits.
b113f53755d581836a9b6d0e09e4c36f32828ca1 – I executed commit without “-M” and entered a multi-lines comment
f448518aa27e6c58e933bd0f62f0c479b1fefb8b – This was done for SourceTree

The 3rd one is interesting because I simply use “Reverse Commit” action from source tree, so it didn’t even prompt me for the commit comment.

Thanks,
Cheng


==>git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean

ml D:\nextinfo
==>git push origin master
Counting objects: 14, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 925 bytes | 0 bytes/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote:
remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)
remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \
remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
remote:    || E ||      || R ||      || R ||      || O ||      || R ||
remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'
remote:
remote:
remote: Push rejected.
remote:
remote: refs/heads/master: f448518aa27e6c58e933bd0f62f0c479b1fefb8b: commit message doesn't match regex: [A-Z0-9\-]+: .*
remote: refs/heads/master: b113f53755d581836a9b6d0e09e4c36f32828ca1: commit message doesn't match regex: [A-Z0-9\-]+: .*
remote: refs/heads/master: 0b699b4aae05d263fc9ddec98d97697fa13e3008: commit message doesn't match regex: [A-Z0-9\-]+: .*
remote:
To http://yeh@stash.cts.cubic.cub/scm/nxinfo/nextinfo.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://yeh@stash.cts.cubic.cub/scm/nxinfo/nextinfo.git'

ml D:\nextinfo
==>git log
commit 0b699b4aae05d263fc9ddec98d97697fa13e3008
Author: Yeh, Cheng <cheng.yeh@cubic.com>
Date:   Tue Apr 21 17:56:58 2015 -0700

    Revert "NEXTINFO-1951: This is another test"

    This reverts commit f448518aa27e6c58e933bd0f62f0c479b1fefb8b.

commit f448518aa27e6c58e933bd0f62f0c479b1fefb8b
Author: Yeh, Cheng <cheng.yeh@cubic.com>
Date:   Tue Apr 21 17:55:31 2015 -0700

    NEXTINFO-1951: This is another test

    Hello

commit b113f53755d581836a9b6d0e09e4c36f32828ca1
Author: Yeh, Cheng <cheng.yeh@cubic.com>
Date:   Tue Apr 21 17:50:32 2015 -0700

    NEXTINFO-1951: This is a test commit Message

    While working on a change

commit c284ae3b25c9700f3011ed0e232b87228c3fccb9
Author: Yeh, Cheng <cheng.yeh@cubic.com>
Date:   Tue Mar 10 20:05:59 2015 -0700

**Comment by christiangalsterer** [comment]
I can confirm that this is a problem. Actually this was already raised in https://github.com/sford/yet-another-commit-checker/issues/15 and there is also patch/sample are available how to fix it. I created a local version of the plugin including the patch and it works like charm. So would be nice to get this fix in the next release soon.

**Comment by sford** [comment]
Hi @ctsyeh ,

Those multi-line commit messages should work fine, but requires the regex to be tweaked. Can you try changing the regex to something like `[A-Z0-9\-]+: (.*|\n)+`. This should allow multi line commit messages like 

```
NEXTINFO-1951: This is a test commit Message

   While working on a change
```
to be match correctly.

Let me know how this goes. This comes up frequently so I think I need to add this to the README :-)

@christiangalsterer , #15 is similar but it involves applying the regex multiple times to collect all matches rather then enforcing a strict commit message structure. #15 as-is would change matching semantics for existing users (either a migration strategy would need to be created or a setting exposed to enable new behavior).

**Comment by christiangalsterer** [comment]
You are actually right. Would be nonetheless nice to get #15 implemented.

**Comment by ctsyeh** [comment]
Thanks Sean.

To cope with the comment below, where the Jira ID is not at the start, I changed to “(Revert )?[A-Z]{3,}\-[0-9]+:(.*|\n)+” and it appears to work for us.


Author: Yeh, Cheng <cheng.yeh@cubic.com<mailto:cheng.yeh@cubic.com>>
Date:   Tue Apr 21 17:56:58 2015 -0700

    Revert "NEXTINFO-1951: This is another test"

    This reverts commit f448518aa27e6c58e933bd0f62f0c479b1fefb8b.


Appreciate your quick response and help.

Cheng

**Comment by sford** [comment]
Glad it worked :+1:
