### ISSUE TITLE
Enable for all repos by default

### ISSUE THREAD

**Issue by tubaguy50035** [sford/yet-another-commit-checker#49]
If this is already a feature, let me know and I'll go away :)

It would be pretty awesome to have this move more towards Stash server settings so that it could be enabled for all repos by default.  I'd love to not have to configure this for all the repos we have.

Then the per repo settings would just override the defaults.

**Comment by tubaguy50035** [comment]
Saw the closed issue that already asks for this.

**Comment by sford** [comment]
Just a FYI, YACC did get global settings recently. If configured, they are enabled for all repositories by default, unless they have their own specific settings. :+1:
