### ISSUE TITLE
YACC doesnot exclude service user commits

### ISSUE THREAD

**Issue by bnannapaneni** [sford/yet-another-commit-checker#52]
Hi Sean,

 I have the following issue with YACC . Our Continuous Integration(CI) team updates a file,creates a tag on it and pushes the tag to the repository. Later,development teams creates a branch over the tag . Issue here is CI team, doesnot use a Jira ticket while pushing a tag and it is preventing users to create branch on it. Everytime I have to disable YACC and get the required branch created. This is the error we get.

remote: refs/heads/2014-GA-RC1_te: 80e097a4ff4d0e6a4dc614e0ff566ba7675a84b3: No JIRA Issue found in commit message.
remote:
remote: refs/heads/2014-GA-RC1_te: d054af83c8b8e70851e903b7098a83938596a9ad: No JIRA Issue found in commit message.

CI team tries to push the tag with the ID "cibuild" and Development Team uses their AD account to login stash and create branches. How do I make sure all the commits made using cibuild ID are excluded? I selected the option in YACC "Exclude Service User Commits" but that doesnot help . Also commit message used by CI Team is "Committing the SCPPBASE.sql " . Can you please suggest me the Regex to be added to get these commits excluded?

Regards,
Bhargavi.

**Comment by sford** [comment]
Hey @bnannapaneni ,

I am not sure I am understanding the full picture... if the dev team is creating a branch from a tag, I would assume the branch's commits are already in the repository, so shouldn't be checked? Maybe something is re-creating commits, ie, creating new commit ids?

If it helps:

> How do I make sure all the commits made using cibuild ID are excluded? I selected the option in YACC "Exclude Service User Commits" but that doesnot help .

This will only exclude service users that authenticate using [SSH access keys for system use](https://confluence.atlassian.com/display/STASH/SSH+access+keys+for+system+use). SSH access keys for system use is generally meant for things like CI servers.

> Also commit message used by CI Team is "Committing the SCPPBASE.sql " . Can you please suggest me the Regex to be added to get these commits excluded?

You could do something as simple as `^Committing` or `^Committing the SCPPBASE\.sql`... that should match those commits.

Hope that helps!

**Comment by bnannapaneni** [comment]
Hi Sean,

 Please see the attached document which has screenshots. As shown in the first screenshot, CI Team does not use any commits while pushing their changes. I'm not very sure about the script they use to push these commits without any Jira issue.

I would like to create a branch on the tag without disabling YACC.

Thanks,
Bhargavi.

**Comment by sford** [comment]
Little difficult to get the full picture of what is going on just from those screenshots, but I am not sure why the exclude regex wouldn't work. You need to look at the commits that YACC is rejecting (find them in `git log`) and create an exclude regex that would match them.

**Comment by bnannapaneni** [comment]
Hi Sean,

 By making few modifications in the commit message and Exclude regex I am able to create any branches without any issues.

Thanks for the help,
Bhargavi.
