### ISSUE TITLE
Installing the hook

### ISSUE THREAD

**Issue by alex131290** [sford/yet-another-commit-checker#53]
Hi, 
I've just downloaded the hook, i was able to install it on my testing environment using the SDK , "atlas-install-plugin", is there any way to install it without using the SDK?
In my understanding i need the *.jar file.

**Comment by agusmba** [comment]
yes, you do not need the sdk at all for installing it.
Download it and upload it to your stash environment as a regular addon.

**Comment by sford** [comment]
As @agusmba mentioned, the marketplace link is https://marketplace.atlassian.com/plugins/com.isroot.stash.plugin.yacc

Also, if your Stash instance has outbound internet, you can also install it using it's built-in add-on manager (ie, `Find new add-ons` on the admin page).

**Comment by alex131290** [comment]
I have another issue: I've enabled the "Require Valid JIRA " and i'm getting this error:
AAA-1: Unable to validate JIRA issue because there was an authentication failure when communicating with JIRA.
remote:
remote: refs/heads/master: 17658b519eb8335222da47dbf10390cf0d5ba8ad: To authenticate, visit http://PC-ABRODOV:7990/stash/plugins/servlet/applinks/oauth/login-dance/authorize?applicationLinkID=2415ca90-6c6a-3668-85b4-0a91e9bcc1a4 in a web browser.

I've already linked my stash with jira, when i'm clicking on the link .
The second problem, i've downloaded the source, and i'm trying to run atlas-debug from the root directory and get a lot of exceptions:

[ERROR] Failed to execute goal com.atlassian.maven.plugins:maven-stash-plugin:5.0.13:unit-test (default-unit-test) on proj
ect yacc: Unable to execute mojo: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Git\repos\yet-another-commit-checker\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sford** [comment]
Regarding the auth error, try following these instructions to verify that Stash can talk to JIRA: https://github.com/sford/yet-another-commit-checker/blob/master/README.md#i-am-getting-a-jira-authentication-failed-message-when-attempting-to-push-my-code-or-when-trying-to-configure-an-issue-jql-matcher . 

No idea about the atlas issue... maybe problem with your setup? YACC is currently compiling and tests passing on Travis CI using atlas sdk.

**Comment by alex131290** [comment]
It's working now, i have another question.
As i saw your hook doesn't support updating commits that were made by the user, let's that i'm using the "Require Valid JIRA " , is it possible to access the summary field of the found jira id, and take the text from this field and amend it to the commit that is being pushed?
Another thing that is not working really good, i'm pushing a commit from windows using the "TortoiseGit" GUI client the jira validation is working fine, i'm trying to push the same commit using the git cli from the same machine (via cmd or Git Bash) it's not finding the jira ID and i'm getting the error from the hook, are you familiar with this ?

**Comment by sford** [comment]
> It's working now,

:+1: 

> take the text from this field and amend it to the commit that is being pushed?

Does git even support this in a pre-receive hook? Amending commits regenerates the commit id. So, if this was done, then every time a commit was amended, the user would have to reset their local branch to the branch on origin to get the amended commits.

>  it's not finding the jira ID and i'm getting the error from the hook, are you familiar with this ?

Depends on what the error is... what error are you getting?

**Comment by alex131290** [comment]
This is the error that i got, while i was trying to push via the command line on my windows: 
remote: refs/heads/feature1: 8dbefa99e574ef633cb4fcbfbfad8dd564e8987b: TLVT-125: JIRA Issue does not exist
I'f i'm trying to push to same commit using the GUI client that i have it's working fine.

**Comment by sford** [comment]
Could you be pushing as different users between the GUI client and command line, as in, different users with different JIRA permissions? Someone could get a "JIRA Issue does not exist" error if they don't have permission to view that issue in JIRA.

**Comment by sford** [comment]
Closing. Feel free to re-open if you have other questions.
