### ISSUE TITLE
Match author with Jira

### ISSUE THREAD

**Issue by ahimmighofen** [sford/yet-another-commit-checker#58]
At the moment I am using YACC to check if there is a Jira ticket ID in the commit messageand if the referenced ticket is 'in progress'. I do this by using the following query:
'assignee is not empty and status="in progress" and project=PRO'

Alas, this is unfortunately not enough to satisfy our strict development process. I also have to check if the user which made the commit is the assignee of the Jira ticket. It would help me a lot if I could use a query like:
'assignee=$commit_user and status="in progress" and project=PRO'

**Comment by sford** [comment]
I do the same thing... we use JQL `currentUser()`, so something like `assignee=currentUser()`. In this context, JIRA currentUser() returns the user that Stash is using to execute the JQL query, which should be the user that is doing the push (the commit user).

**Comment by ahimmighofen** [comment]
Thank you very much!
