### ISSUE TITLE
Exclude users

### ISSUE THREAD

**Issue by alex131290** [sford/yet-another-commit-checker#61]
Hi, 
Is there anyway to allow specific users to push without executing the hook or maybe you have some options in your hook where i can pre define a few users, most of the times it will be admins and builders.

**Comment by sford** [comment]
Whitelisting users isn't supported, but it wouldn't be difficult to add support. Maybe an option that accepts a comma delimited list of stash user names to skip checks for? Pull requests are welcome :-)

You could also use the 'exclude by regex' option to add support to skip checks on a per-commit basis if they include `#skipchecks`. Depending on your workflow, this might be a safer option compared to skipping all checks from a user incase there are times when they should be including jira ids or what not for normal development.

**Comment by sford** [comment]
Closing. Feel free to re-open if you have other questions.

**Comment by christiangalsterer** [comment]
I would like to request to reopen this issue. We also have the need to exclude a particular user and using regex is not an option. I would also provide a PR if you are OK with the request in general.

**Comment by christiangalsterer** [comment]
I spent some time looking into it and change was rather easy and would be ready to submit a PR, but wanted to here your feedback if you are interested.

**Comment by sford** [comment]
@christiangalsterer Thanks for checking regarding a PR. I am OK with it... PR would be much appreciated :-)

**Comment by christiangalsterer** [comment]
ok, great. Just opened a PR. Please let me know in case of any needed changes.

**Comment by sford** [comment]
#146 merged 👍
