### ISSUE TITLE
Exclude Service User Commits

### ISSUE THREAD

**Issue by alex131290** [sford/yet-another-commit-checker#65]
How do i use this feature ?
Is it going to work with builder users ?

**Comment by sford** [comment]
Hey @alex131290 ,

Check out the YACC documentation to learn how to use it: https://github.com/sford/yet-another-commit-checker#exclude-service-user-commits

The YACC documentation links [Stash documentation](https://confluence.atlassian.com/display/STASH/SSH+access+keys+for+system+use) for more information. Basically, you need to install SSH access keys to a repository or a project.

**Comment by sford** [comment]
Closing. Feel free to re-open if you have other questions.
