### ISSUE TITLE
Multiple committers - pull request workflow

### ISSUE THREAD

**Issue by bsacks99** [sford/yet-another-commit-checker#66]
I have a question about YACCs behavior in a pull request workflow environment. If one users branches from master will YACC allow multiple committers to push to that new branch? We are having an issue where it appears to be requiring the user who created the branch only. We aren't sure if this is a configuration issue with other aspects of stash, or an issue with how YACC is configured.

**Comment by sford** [comment]
Hi @bsacks99 ,

That should work fine. At least, that is how we use YACC. We branch from master, use pull requests, and we occasionally have multiple committers on the PR's branch.

Is YACC preventing the push? If so, what is the error?

**Comment by bsacks99** [comment]
Thanks for the response. This turned out to be an SSH key issue. One user was using a key that had been added to another uses stash account. YACC is doing it's job fine and did the right thing catching that issue for us.

**Comment by sford** [comment]
Cool! Glad you figured out the issue, and that YACC was doing it's job!
