### ISSUE TITLE
Add global configuration

### ISSUE THREAD

**Issue by jimbethancourt** [sford/yet-another-commit-checker#67]
Adding the ability to set a system-wide configuration that can be overridden by a repository configuration if one is present.  This will provide a safety net for new projects and make policies easier to set and update for large medium to large Stash installations.

**Comment by aramalipoor** [comment]
:+1:

**Comment by djlindstr** [comment]
This is a great feature. Are there any plans for an official 1.7 release? Lots of good stuff has happened since 1.6.

**Comment by sford** [comment]
Thanks for your interest! Yes, there will be an official 1.7 release very
soon. I wanted to get a selenium integration test around the new config
page... Almost done with it. Will try to get the release out this weekend.
Thanks!

**Comment by sford** [comment]
1.7 released!
