### ISSUE TITLE
bitbucket server 4 support

### ISSUE THREAD

**Issue by sford** [sford/yet-another-commit-checker#76]
Bitbucket Server 4 support is being done in the `stash4` branch. Almost done, will be pushed to marketplace soon.

**Comment by agusmba** [comment]
I just got notice of the rebrand change and you're almost ready! Thanks!

**Comment by sford** [comment]
:+1:  

There is an intermittent test failure I need to iron out, some minor doc changes, and a bit of manual testing left to do, but it is really close.

**Comment by sford** [comment]
YACC 1.9 pushed to atlassian marketplace
