### ISSUE TITLE
Push of git notes failes, multiple issues.

### ISSUE THREAD

**Issue by SambalOelek** [sford/yet-another-commit-checker#78]
git notes thrives in refs/notes/*

1. All git notes commits are checked every time - not just the latest.  
  If user B adds a note, the   `git push origin refs/notes/commits`
  will get shot down if user A has ever committed and pushed a git notes.
2. git notes commit comments are auto generated => problem.

Pretty please fix!

**Comment by sford** [comment]
Today I learned: git notes is a thing!

Thanks for the heads up, I will check that out... sounds like this is something YACC just needs to look for and ignore. :+1:

**Comment by sford** [comment]
Fix merged, will be in next release
