### ISSUE TITLE
Feature request: configuration per stash/bitbucket PROJECT

### ISSUE THREAD

**Issue by Rudy-Tmc** [sford/yet-another-commit-checker#79]
Hi Sean,

First of all this plugin rocks! It should be a first class citizen of Stash/Bitbucket.
And I do like your recent addition of the global configuration in stead of the per repo configuration.
But could you also please make a per project configuration possible? So all repo's in a certain
project will be configured the same. It will save us loads of configuration time.

Thanks
Rudy

**Comment by sford** [comment]
Thanks for the kind words :-)

I was initially thinking this might be a lot of work, but the existing global hook could probably be used to implement this. I think a per-project settings page would just need to be created, and then the global hook updated to look for these settings before trying to apply the global settings.

**Comment by sford** [comment]
I know this is an old ticket ~ but just wanted to mention that BBS 5.2.0 now supports [project level hooks](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-2-release-notes-917966093.html). If YACC doesn't already work with it, I will make sure the appropriate changes are made to ensure YACC supports this.

**Comment by sford** [comment]
Closing in favor of  #165
