### ISSUE TITLE
Commit Message Regex not working

### ISSUE THREAD

**Issue by stevenraylane** [sford/yet-another-commit-checker#80]
I've tried a series of different expressions, including the sample and each fails with "commit message doesn't match regex".  

COMMIT_EDITMSG:
>
> DSM-51247: minor tweaks to sql code for performance
>
> Signed-off-by: Steven Lane <xxxx@xxxx>
>

Commit Message Regex:
> [A-Z]+-[0-9]+.*

Error message:
> remote: refs/heads/DSM-Hot-Fixes: 73ec942145fcdcb443bc1572686584f1c1905107: commit message doesn't match regex: [A-Z]+-[0-9]+.*

Any thoughts?

**Comment by sford** [comment]
That looks like a multi-line commit message (with the Sign off). Can you check out https://github.com/sford/yet-another-commit-checker#multi-line-commit-messages to see if that helps?

**Comment by Rudy-Tmc** [comment]
Steven,

Use:
([A-Z]+-[0-9]+)(.*|\n)+
or
(\w+-\d+)(.*|\n)+

I hope this helps,
Rudy

**Comment by stevenraylane** [comment]
That worked. Thanks.

**Comment by sford** [comment]
:+1:

**Comment by Alonkr** [comment]
hi i need some help i tring to add some pattern commit that will be with #NNN with description before and after , i am trying this regex on Commit Message Regex : ([A-Z]+-#[0-9][0-9][0-9]+)(.|\n)+
and on the exclide this regex : ^Revert \"|#skipchecks
please help how to do that trick work ? 
exsample commit : 
Issue #856 - Implement CR60 - Add getTelephoneNumberExchangeListoperation to BillerPhone
