### ISSUE TITLE
Permission denied on packfile after YACC blocks a push

### ISSUE THREAD

**Issue by Jaap-TMC** [sford/yet-another-commit-checker#85]
In a specific situation we get a permission denied on the packfile.

We use the YACC plugin to check name and mail (and other checks). We do merges over repo's in a specific developer branch. Meaning that a lot of commits are part of the merge commit. This results in an blocked push by YACC because those commits are related to other users. 

In this specific case we disable the YACC plugin so the developer can push the merge commit. After disabling this name/mail check the push fails due to the permission denied on the pack file because the packfile remains on the Bitbucket server.

To bypass this error we can change the push content and push again, and in that case a new pack file is created and the permission denied does not occur.

I don't see the same error on regular basis, and as far as I can see only when merging over repo's. 

Is this something that can be solved in the YACC plugin or is this to be solved by Bitbucket?

Part of the error message:
remote: error: unable to write sha1 filename ./objects/pack/pack-e437bfb4b318aa7f1e3ce42db82c041e58008b65.pack: Permission denied[K
remote: fatal: cannot store pack file[K
error: unpack failed: index-pack abnormal exit
To ssh://git@devstash.acc.vanderlande.com:7999/san/packfile_check.git
 ! [remote rejected] master -> master (unpacker error)

**Comment by sford** [comment]
Hey @Jaap-TMC ,

That permission denied error looks like it might be file system related. I am not sure if it can be solved in YACC.... if this was my system, I would probably check the BitBucker Server data directory (where all the git repos are stored) and verify that the permissions are correct, as in, the user BitBucker Server is running as can read and write to those files.

**Comment by sford** [comment]
Going to close this because I don't think this is YACC related. Feel free to re-open if needed.
