### ISSUE TITLE
Is it possible to enforce that the assignee is the person pushing?

### ISSUE THREAD

**Issue by djmills32** [sford/yet-another-commit-checker#89]
Hi, love your add-on so far.

Just wondering, your recommended JQL is
    assignee is not empty and status="in progress"

Is the id of the person attempting the push available?  So would the following be possible
    assignee = $current.user and status="in progress"

where "$current.user" is replaced with whatever makes it available.

If not, can this be a feature request.  Either via the above mechism or another tick box grouped with the first 2 "Require Matching Commiter Email/Name" - e.g. "Require Matching Commiter Assignment" - "Require that the Jira ticket is currently assigned to the committing user.

**Comment by sford** [comment]
Hey @djmills32 , the id of the person doing the push should be available using the `currentUser()` JQL function. So, you should be able to do `assignee=currentUser() and status='in progress'`. Let me know if that works for you!

**Comment by djmills32** [comment]
Hi Sean,

That works a treat – thank you.

Is there a list somewhere of what other variables/functions are available?

Also, if I may ask another question, we have found that if a user separates their commit comments over multiple lines:
                e.g.
                                Committing to branch: release/1.04-gradle
User commit comments:
ISCM-883: "OWNER" users were not being granted "IMED SUPPORT" application group.

The this gets rejected as it fails to match the regexp.  I even added “.*” both at the start and end of the regexp – to no avail.  Is there some way around this?  The first 2 lines were generated by a “commit-msg” hook – which I have had to disable to get things working.

Regards,

David Mills | DelPHI Senior Technical Analyst | Medibank Private
Level 2, 720 Bourke Street, Docklands, VIC, 3008 | Tel: 03 8622 5346 | Mob: 0411 513 404

**Comment by sford** [comment]
> Is there a list somewhere of what other variables/functions are available?

Any valid JQL query can be used... a list of JQL functions can be found at https://confluence.atlassian.com/jira/advanced-searching-functions-338363497.html

> Also, if I may ask another question, we have found that if a user separates their commit comments over multiple lines:

By default, `.*` doesn't match newlines. So, you might need to do something like `(.|\n)*`

https://github.com/sford/yet-another-commit-checker#multi-line-commit-messages has some more information regarding less.

Hope this helps!

**Comment by djmills32** [comment]
Thanks very much for your help.


Regards,

David Mills | DelPHI Senior Technical Analyst | Medibank Private
Level 2, 720 Bourke Street, Docklands, VIC, 3008 | Tel: 03 8622 5346 | Mob: 0411 513 404

**Comment by sford** [comment]
:+1:  

going to close this
