### ISSUE TITLE
YACC uses a lot of JVM heap for org.eclipse.jgit objects -- can cause OOME under heavy load

### ISSUE THREAD

**Issue by cszmajda** [sford/yet-another-commit-checker#97]
We had YACC 1.10 installed on one of our production Data Center instances.  One of the nodes suddenly locked up in GC even though we generally run with 500+ MBytes of headroom in JVM heap.

![screen shot 2015-12-21 at 10 41 18 am](https://cloud.githubusercontent.com/assets/7602097/11920989/3eb5ca04-a7d1-11e5-9c25-b11137f09112.png)

Analysis of a heap dump showed 589 MBytes of JVM memory used by jgit objects. The only code in Bitbucket Server core or plugins on this instance that use jgit is YACC. It appears to keep a lot of jgit packfile objects (read from git repositories?) in memory instead of streaming or forking out to git.

![screen shot 2015-12-18 at 1 02 09 pm](https://cloud.githubusercontent.com/assets/7602097/11920984/2d8b7d6e-a7d1-11e5-8cf9-f1a246b5dbeb.png)

![screen shot 2015-12-18 at 1 03 40 pm](https://cloud.githubusercontent.com/assets/7602097/11920992/4b2f4ad0-a7d1-11e5-9d4e-a5cf2d243f1d.png)

The cluster node did not recover and required manual restart. Luckily only one node was affected, so there was little or no loss of availability.

Can the JVM heap usage of YACC be reduced or limited in some way?  We've had to uninstall YACC from our production instances due to this issue.

**Comment by sford** [comment]
Hey @cszmajda, thanks for the very detailed bug report! 

I did some spot checking of the YACC code and discovered a couple areas where jGit resources were not closed. I could imagine that could potentially cause heap problems.

Are you able to correlate this incident with a particular push or repository? I am wondering if cleaning up the jGit resources is enough, or if the push/packfile objects are large enough where jGit just doesn't have enough heap given your memory settings. If it is the latter, the fix might be more extensive.

**Comment by cszmajda** [comment]
But why does YACC need to read the packfile objects into memory in the first place?  Won't this use much more JVM memory than streaming the commit logs with native `git`?

**Comment by sford** [comment]
Fixed in 525e6fcc2 and #139
