### ISSUE TITLE
Initial pushes failing when YACC isn't enabled on the repo for Stash 3.x

### ISSUE THREAD

**Issue by marlang** [sford/yet-another-commit-checker#99]
Will you be fixing Issue 92 for Stash 3.x?

**Comment by sford** [comment]
Hey @marlang , continuing from #92 

```
Thanks for the quick response.  To downgrade, do you know if we lose previous settings?  I can't just upload 1.6 to downgrade, I will need to uninstall it and re-install and I'm not sure what that will do to previously entered settings.
```

I just tested this using `atlas-run` from the Atlassian SDK and my settings remained the same. I installed YACC 1.12-SNAPSHOT, configured repo settings, uninstalled YACC, and then installed YACC 1.9. Afterwards, my repo settings were the same as before. 

So, settings _should_ be fine. However, as a standard disclaimer, I would strongly suggest using the Stash Backup Client to make a backup just in case.
